const abi_erc20 = [
  {
    "constant":true,
    "inputs":[
       
    ],
    "name":"token0",
    "outputs":[
       {
        "name":"",
        "type":"address"
       }
    ],
    "payable":false,
    "type":"function"
 },
 {
  "constant":true,
  "inputs":[
     
  ],
  "name":"token1",
  "outputs":[
     {
        "name":"",
        "type":"address"
     }
  ],
  "payable":false,
  "type":"function"
 }, 
 {
     "constant":true,
     "inputs":[
        
     ],
     "name":"name",
     "outputs":[
        {
           "name":"",
           "type":"string"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        
     ],
     "name":"name",
     "outputs":[
        {
           "name":"",
           "type":"string"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        
     ],
     "name":"owner",
     "outputs":[
        {
           "name":"",
           "type":"address"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        
     ],
     "name":"decimals",
     "outputs":[
        {
           "name":"",
           "type":"uint8"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        {
           "name":"_owner",
           "type":"address"
        }
     ],
     "name":"balanceOf",
     "outputs":[
        {
           "name":"balance",
           "type":"uint256"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        
     ],
     "name":"symbol",
     "outputs":[
        {
           "name":"",
           "type":"string"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        
     ],
     "name":"totalFees",
     "outputs":[
        {
           "name":"",
           "type":"uint256"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        
     ],
     "name":"burned",
     "outputs":[
        {
           "name":"",
           "type":"uint256"
        }
     ],
     "payable":false,
     "type":"function"
  },
  {
     "constant":true,
     "inputs":[
        
     ],
     "name":"totalSupply",
     "outputs":[
        {
           "name":"",
           "type":"uint256"
        }
     ],
     "payable":false,
     "type":"function"
  }
]

export { abi_erc20 }